### ISSUE TITLE
Common Deployment infrastructure

### ISSUE THREAD

**Issue by ruromero** [open-accelerators/mercury#20]
### Description of Problem:
As part of the development enablement process a common set of requirements have been identified shared by any Functional Pattern. For that whenever provisioning a new development environment for any given BIAN Service Domain the following infrastructure components will be deployed or shared:

- [ ] Message broker: For state change notification and asynchronous command request
- [ ] Identity Provider: For securing one or many development tools
- [ ] Mocking Tool: For development and integration testing
- [ ] Monitoring: For analytics, traceability and alerting
- [ ] Enterprise Integration Platform: For message routing and transformation

Depending on the purpose of each environment (dev/test/prod/...) some elements will not make sense or have to be provisioned differently.

### Potential Solutions:
A possible solution could be an operator that leverages other operators for provisioning each of the required common artefacts or provide the configuration flexibility to integrate them with other existing ones.

**Comment by ilan-pinto** [comment]
- having OCP YAML files for  Message broker(Kafka), Identity Provider(Keycloack), Mocking Tool(microcs)
https://github.com/open-accelerators/mercury/issues/21
